# This is a basic workflow to help you get started with Actions

name: cron-netlify-build

# Controls when the action will run. 
on:
  schedule:
    - cron: '15 4 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: post netlify build hook
        run: curl --silent -X POST -d {} https://api.netlify.com/build_hooks/5e80430a75aa64ff290711f0

